version: '3.4'

services:
  api:
    depends_on:
      - mongo_db
      - postgres_db
    build:
      context: .
      dockerfile: Dockerfile
    command: npm run start:prod
    environment:
      APPLICATION_PORT: 3006
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    ports:
      - '13610:3006'

  mongo_db:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - '27017:27017'

  postgres_db:
    image: postgres:10.14
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - '5432:5432'
