version: '3.4'

services:
  api:
    depends_on:
      - mongo_db
      - postgres_db
    build:
      context: .
      dockerfile: Dockerfile
    command: npm run start:prod
    environment:
      APPLICATION_PORT: 3006
      DB_HOST: mongo_db
      DB_NAME: games
      DB_PORT: 27017
      DB_USER: root
      DB_PASSWORD: Password123
    ports:
      - '13610:3006'

  mongo_db:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: Password123
    ports:
      - '27017:27017'

  postgres_db:
    image: postgres:10.14
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: root
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
